import requests

class MyWeatherApi:
    def __init__(self, gen_api_key):
        self.api_key = gen_api_key
        self.base_url = "http://api.openweathermap.org/data/2.5/weather"

    def get_weather(self, city):
        params = {
            'q': city,
            'appid': self.api_key,
            'units': 'metric'
        }

        try:
            response = requests.get(self.base_url, params=params)
            response.raise_for_status()                              # Check for errors in the HTTP response
            return response.json()
        except requests.exceptions.RequestException as e:
            print(f"Error fetching weather data: {e}")
            return None

    def display_weather(self, weather_data):
        if weather_data:
            print(f"Weather in {weather_data['name']}, {weather_data['sys']['country']}:") 
            print(f"Temperature: {weather_data['main']['temp']}°C")
            print(f"Description: {weather_data['weather'][0]['description']}")
            print(f"Humidity: {weather_data['main']['humidity']}%")
            print(f"Wind Speed: {weather_data['wind']['speed']} m/s")
        else:
            print("Failed to fetch weather data.")

if __name__ == "__main__":
    gen_api_key = "7ad7fd7ee4a98bcc22f1d34b1f4d33ae"    # my api key , generated by creating a account onto the OpenWeatherAPI
    
    cities = ["Pune", "Nashik", "Mumbai", "Nagpur"]  # Add more cities if needed

    weather_app = MyWeatherApi(gen_api_key)

    for city in cities:
        print("\n------------------------")
        print(f"Fetching weather for {city}...")
        weather_data = weather_app.get_weather(city)
        weather_app.display_weather(weather_data)



 
